//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAPEntities : DbContext
    {
        public SAPEntities()
            : base("name=SAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FI03_AT_DocItem> FI03_AT_DocItem { get; set; }
        public DbSet<FI03_AT_RecCostCenter> FI03_AT_RecCostCenter { get; set; }
        public DbSet<HR01_Employee> HR01_Employee { get; set; }
        public DbSet<FI03_AT_Doc> FI03_AT_Doc { get; set; }
        public DbSet<FI03_AT_FlowApprove> FI03_AT_FlowApprove { get; set; }
        public DbSet<vAssetTransfer_Doc> vAssetTransfer_Doc { get; set; }
        public DbSet<vAssetTransfer_Flow> vAssetTransfer_Flow { get; set; }
        public DbSet<FI03_AT_CostCenter> FI03_AT_CostCenter { get; set; }
        public DbSet<FI03_AT_FlowMaster> FI03_AT_FlowMaster { get; set; }
        public DbSet<MM01_PR_Config> MM01_PR_Config { get; set; }
        public DbSet<vAssetTransfer_Report> vAssetTransfer_Report { get; set; }
        public DbSet<FI03_AT_FlowApprove_Log> FI03_AT_FlowApprove_Log { get; set; }
        public DbSet<FI03_AT_RecCostCenter_Special> FI03_AT_RecCostCenter_Special { get; set; }
        public DbSet<vAssetTransfer_ReportHistory> vAssetTransfer_ReportHistory { get; set; }
    }
}
