//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI03_AT_DocItem
    {
        public string Client { get; set; }
        public System.Guid AutoRun { get; set; }
        public Nullable<System.Guid> FI03_AT_Doc { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public string AssetClass { get; set; }
        public string Asset { get; set; }
        public string AssetDescription { get; set; }
        public string CostCenter { get; set; }
        public string Room { get; set; }
        public Nullable<int> Qty { get; set; }
        public string RecCostCenter { get; set; }
        public string CostCenter2 { get; set; }
        public string Room2 { get; set; }
        public string Remark { get; set; }
    }
}
