//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI03_AT_Doc
    {
        public string Client { get; set; }
        public System.Guid AutoRun { get; set; }
        public string DocNo { get; set; }
        public string CreateDate { get; set; }
        public string FI03_AT_RecCostCenter_From { get; set; }
        public string FI03_AT_RecCostCenter_To { get; set; }
        public string IssueBy { get; set; }
        public string IssueDate { get; set; }
        public string IssueByTop { get; set; }
        public string IssueDateTop { get; set; }
        public string ReceiveBy { get; set; }
        public string ReceiveDate { get; set; }
        public string ReceiveByTop { get; set; }
        public string ReceiveDateTop { get; set; }
        public string AFApp { get; set; }
        public string AFAppDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreateTime { get; set; }
        public string CreateBy { get; set; }
        public string UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateTime { get; set; }
        public string DocStatus { get; set; }
        public string FlowStatus { get; set; }
        public string IssueTime { get; set; }
        public string IssueTimeTop { get; set; }
        public string ReceiveTime { get; set; }
        public string ReceiveTimeTop { get; set; }
        public string AFAppTime { get; set; }
    }
}
