//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI03_AT_RecCostCenter_Special
    {
        public string Client { get; set; }
        public System.Guid AutoRun { get; set; }
        public string SectionCode { get; set; }
        public string FieldCode { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
