//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR01_Employee
    {
        public string Client { get; set; }
        public string EmpID { get; set; }
        public string CompanyName { get; set; }
        public string EmpStatus { get; set; }
        public string WorkShift { get; set; }
        public string JobTitleCode { get; set; }
        public string JobTitleName { get; set; }
        public string PositionTitleCode { get; set; }
        public string PositionTitleName { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string SectionCode { get; set; }
        public string SectionName { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionName { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string TeamCode { get; set; }
        public string TeamName { get; set; }
        public string NamePrefix { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NamePrefixEN { get; set; }
        public string FirstNameEN { get; set; }
        public string LastNameEN { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> StartWorkDate { get; set; }
        public Nullable<System.DateTime> StartPermanent { get; set; }
        public Nullable<System.DateTime> EndWorkDate { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> SendMailFC { get; set; }
        public Nullable<bool> SendMailSO { get; set; }
        public Nullable<bool> SendMailComparing { get; set; }
        public string DivisionCodeRef { get; set; }
        public string DepartmentCodeRef { get; set; }
        public string SectionCodeRef { get; set; }
        public string PositionCodeRef { get; set; }
        public string TeamCodeRef { get; set; }
        public string EmpIDCard { get; set; }
    }
}
