//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM01_PR_Config
    {
        public string Client { get; set; }
        public System.Guid ID { get; set; }
        public string Description { get; set; }
        public string Movement { get; set; }
        public string Active { get; set; }
    }
}
