//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAssetTransfer_Report
    {
        public string Client { get; set; }
        public System.Guid AutoRun { get; set; }
        public string DocNo { get; set; }
        public string CreateDate { get; set; }
        public string FI03_AT_RecCostCenter_From { get; set; }
        public string ReceiverCC_From { get; set; }
        public string FI03_AT_RecCostCenter_To { get; set; }
        public string ReceiverCC_to { get; set; }
        public System.Guid AutoRunItem { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public string AssetClass { get; set; }
        public string Asset { get; set; }
        public string AssetDescription { get; set; }
        public string CostCenter { get; set; }
        public string Room { get; set; }
        public Nullable<int> Qty { get; set; }
        public string RecCostCenter { get; set; }
        public string CostCenter2 { get; set; }
        public string Room2 { get; set; }
        public string Remark { get; set; }
        public string fsIssuer { get; set; }
        public string IssuerID { get; set; }
        public string IssuerName { get; set; }
        public string IssuerEmail { get; set; }
        public string IssuerAppStatus { get; set; }
        public string IssuerAppDate { get; set; }
        public string IssuerAppTime { get; set; }
        public string IssuerRemark { get; set; }
        public string fsTopIssuer { get; set; }
        public string TopIssuerID { get; set; }
        public string TopIssuerName { get; set; }
        public string TopIssuerEmail { get; set; }
        public string TopIssuerAppStatus { get; set; }
        public string TopIssuerAppDate { get; set; }
        public string TopIssuerAppTime { get; set; }
        public string TopIssuerRemark { get; set; }
        public string fsReciever { get; set; }
        public string RecieverID { get; set; }
        public string RecieverName { get; set; }
        public string RecieverEmail { get; set; }
        public string RecieverAppStatus { get; set; }
        public string RecieverAppDate { get; set; }
        public string RecieverAppTime { get; set; }
        public string RecieverRemark { get; set; }
        public string fsTopReciever { get; set; }
        public string TopRecieverID { get; set; }
        public string TopRecieverName { get; set; }
        public string TopRecieverEmail { get; set; }
        public string TopRecieverAppStatus { get; set; }
        public string TopRecieverAppDate { get; set; }
        public string TopRecieverAppTime { get; set; }
        public string TopRecieverRemark { get; set; }
        public string fsAF { get; set; }
        public string AFID { get; set; }
        public string AFName { get; set; }
        public string AFEmail { get; set; }
        public string AFAppStatus { get; set; }
        public string AFAppDate { get; set; }
        public string AFAppTime { get; set; }
        public string AFRemark { get; set; }
        public string DocStatus { get; set; }
    }
}
