//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAssetTransfer_Doc
    {
        public string Client { get; set; }
        public System.Guid AutoRun { get; set; }
        public string DocNo { get; set; }
        public string CreateDate { get; set; }
        public string FI03_AT_RecCostCenter_From { get; set; }
        public string ReceiverCC_From { get; set; }
        public string FI03_AT_RecCostCenter_To { get; set; }
        public string ReceiverCC_to { get; set; }
        public System.Guid AutoRunItem { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public string AssetClass { get; set; }
        public string Asset { get; set; }
        public string AssetDescription { get; set; }
        public string CostCenter { get; set; }
        public string Room { get; set; }
        public Nullable<int> Qty { get; set; }
        public string RecCostCenter { get; set; }
        public string CostCenter2 { get; set; }
        public string Room2 { get; set; }
        public string Remark { get; set; }
        public string DocStatus { get; set; }
        public string FlowStatus { get; set; }
    }
}
